# Generated by Django 3.2.2 on 2021-06-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='経度'),
        ),
    ]
