# Generated by Django 3.2.2 on 2021-06-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmap', '0003_auto_20210603_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='緯度'),
        ),
    ]
