# Generated by Django 3.2.2 on 2021-06-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmap', '0004_alter_customer_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='carbohydrate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='炭水化物'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='脂質'),
        ),
        migrations.AddField(
            model_name='customer',
            name='menu',
            field=models.TextField(blank=True, null=True, verbose_name='メニュー'),
        ),
        migrations.AddField(
            model_name='customer',
            name='openingtime',
            field=models.IntegerField(blank=True, null=True, verbose_name='営業時間'),
        ),
        migrations.AddField(
            model_name='customer',
            name='parking',
            field=models.BooleanField(blank=True, null=True, verbose_name='駐車場'),
        ),
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='値段'),
        ),
        migrations.AddField(
            model_name='customer',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='タンパク質'),
        ),
        migrations.AddField(
            model_name='customer',
            name='snsimage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=20, verbose_name='店名'),
        ),
    ]
