# Generated by Django 3.2.2 on 2021-05-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carbohydrate', models.IntegerField()),
                ('menu', models.TextField()),
                ('address', models.TextField()),
                ('storename', models.TextField()),
                ('snsimage', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('openinngtime', models.IntegerField()),
                ('parking', models.BooleanField()),
            ],
        ),
    ]
