# Generated by Django 3.2.2 on 2021-05-14 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promodel',
            old_name='openinngtime',
            new_name='openingtime',
        ),
    ]
